meta_product_name: "Project Manager"
meta_title: "WOlf Project Manager - Let's help you to arrange, manage your projects and also define all tasks for each project"
meta_description: "Relevant description"
meta_image: "cover.jpg"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
